sudo: required
services:
  - docker

before_install:
  - docker build -t jeroenrijks/ci-with-docker-practice -f Dockerfile.dev .

script:
  - docker run jeroenrijks/ci-with-docker-practice npm run test -- --coverage